// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_87Stomf-vdbJP1atQq64W8lfhJyprwc',
    appId: '1:19449057741:android:a7bb06764017bb0ec8f484',
    messagingSenderId: '19449057741',
    projectId: 'pawsome-stays-de982',
    storageBucket: 'pawsome-stays-de982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvorZDVoyD6sX6JizKYmAJ6vDnz-QWVeM',
    appId: '1:19449057741:ios:88381b4e4a94acf5c8f484',
    messagingSenderId: '19449057741',
    projectId: 'pawsome-stays-de982',
    storageBucket: 'pawsome-stays-de982.appspot.com',
    iosBundleId: 'com.example.pawsomeStays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvorZDVoyD6sX6JizKYmAJ6vDnz-QWVeM',
    appId: '1:19449057741:ios:88381b4e4a94acf5c8f484',
    messagingSenderId: '19449057741',
    projectId: 'pawsome-stays-de982',
    storageBucket: 'pawsome-stays-de982.appspot.com',
    iosBundleId: 'com.example.pawsomeStays',
  );
}
